# Generated by Django 5.2.4 on 2025-07-29 17:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Activo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('location', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número de Serie')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Compra')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Último Mantenimiento')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Próximo Mantenimiento')),
                ('status', models.CharField(choices=[('operational', 'Operacional'), ('under_maintenance', 'En Mantenimiento'), ('retired', 'Retirado'), ('critical', 'Crítico')], default='operational', max_length=20, verbose_name='Estado')),
                ('asset_type', models.CharField(choices=[('vehicle', 'Vehículo'), ('machine', 'Máquina'), ('building', 'Edificio'), ('tool', 'Herramienta'), ('equipment', 'Equipo General'), ('other', 'Otro')], default='equipment', max_length=50, verbose_name='Tipo de Activo')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fabricante')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('warranty_end_date', models.DateField(blank=True, null=True, verbose_name='Fin de Garantía')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'ordering': ['name'],
            },
        ),
    ]
