# Generated by Django 5.2.4 on 2025-07-30 00:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la Pieza')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='SKU/Número de Parte')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad en Stock')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación de Almacén')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Unitario')),
                ('supplier', models.CharField(blank=True, max_length=255, null=True, verbose_name='Proveedor Principal')),
                ('reorder_point', models.IntegerField(default=0, verbose_name='Punto de Reorden')),
                ('last_reordered_date', models.DateField(blank=True, null=True, verbose_name='Última Reorden')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pieza',
                'verbose_name_plural': 'Piezas',
                'ordering': ['name'],
            },
        ),
    ]
